apiVersion: v1
kind: Service
metadata:
  name: workout-service
spec:
  selector:
    app: workout
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout
spec:
  selector:
    matchLabels:
      app: workout
  replicas: 3
  template:
    metadata:
      labels:
        app: workout
    spec:
      containers:
      - name: workout-change
        image: workout-change:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080